---
version: '3'
services:
  jdownloader-2:
    image: jlesage/jdownloader-2
    container_name: jd2
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - MYJDOWNLOADER_EMAIL=
      - MYJDOWNLOADER_PASSWORD=
      - MYJDOWNLOADER_DEVICE_NAME=
      - JDOWNLOADER_HEADLESS=
    volumes:
      - /opt/docker/config/jdownloader-2:/config
      - /opt/5TB/Downloads:/downloads
    restart: unless-stopped
  gluetun:
    image: qmcgaw/gluetun
    container_name: gluetun
    environment:
      - PUID=1000
      - PGID=1000
      - VPN_SERVICE_PROVIDER=nordvpn
      - OPENVPN_USER=
      - OPENVPN_PASSWORD=
      - SERVER_COUNTRIES=Netherlands
      - SERVER_REGIONS=Europe
    volumes:
      - /opt/docker/config/gluetun:/gluetun
    ports:
      - 5800:5800 # Webinterface
      - 3129:3129 # MYJD
    cap_add:
      - NET_ADMIN
    restart: unless-stopped
