version: '3.9'
services:
    gluetun:
        image: qmcgaw/gluetun
        container_name: gluetun
        environment:
            - PUID=1000
            - PGID=1000
            - VPN_SERVICE_PROVIDER=nordvpn
            - OPENVPN_USER=
            - OPENVPN_PASSWORD=
            - SERVER_REGIONS=Netherlands
        volumes:
            - ./configs/gluetun/config:/gluetun
        ports:
            - 3129:3129 #myjd
        cap_add:
            - NET_ADMIN
        restart: unless-stopped
    
    jdownloader2-headless:
        network_mode: "service:gluetun"
        image: plusminus/jdownloader2-headless
        volumes:
            - "/mnt/onedrive/:/jdownloader/downloads/"
            - "./configs/downloader2/config/:/jdownloader/cfg/"
        environment:
            - PASSWORD=
            - EMAIL=
        container_name: jd2
